### ISSUE TITLE
Allow HTML?

### ISSUE THREAD

**Issue by snipe** [MisterPhilip/maintenance-mode#10]
Hi there - thanks for a handy library! Would it be possible to allow HTML in future versions? Would love to be able to link up the email address used in the down message.

**Comment by awjudd** [comment]
@snipe If you publish the assets, you could always just change the `view` which it uses to publish to.  That may be the easiest and even cleanest way.  Though, I was thinking maybe we could make it so you could inject a view.

**Comment by snipe** [comment]
Thanks!

**Comment by MisterPhilip** [comment]
Added in 1.0.3.
