### ISSUE TITLE
Laravel 5.3

### ISSUE THREAD

**Issue by snipe** [MisterPhilip/maintenance-mode#11]
Hi again! Do you know when you might be able to update this for Laravel 5.3? (I know it was just announced today, so not trying to be a pest, just curious. I can't upgrade my app to 5.3 because of this dependency, so looking forward to a new version.)

Also, is there anything I can do to help get you there faster?

**Comment by MisterPhilip** [comment]
Should be a quick change, just need to updated the composer.json to allow for it - I doubt anything in 5.3 broke our code, but I can look tonight.

**Comment by snipe** [comment]
The upgrade guide looks like it could be nasty for other packages (especially for a point upgrade - ugh), but seems pretty low-key for what your package does (no database interactions so no collections to deal with, etc): https://www.laravel.com/docs/5.3/upgrade#upgrade-5.3.0

**Comment by MisterPhilip** [comment]
So it actually looks like this package is _mostly_ rolled up into 5.3, actually. You can't specify a view, but they do allow message and retry now: https://laravel.com/docs/5.3/configuration#maintenance-mode

**Comment by MisterPhilip** [comment]
OK, finally had some time to work on it. For the most part it works, but custom views do not. I'm looking into a more eloquent way to allow for it, but right now it looks like it's going to be "insert a few lines of code into your `App\Exceptions\Handler::render()` method". The code is on the dev branch if you want to test/play with it.

**Comment by MisterPhilip** [comment]
I'm closing this out since 5.3 is a several versions old, but if you still need a backfill let me know. It'll take a little bit of work, but I can see if I can squeeze in some time to figure it out. Otherwise, the latest releases of this package will work on Laravel 5.5 & 5.6. Sorry I never got a chance to get around to it back then :(
