### ISSUE TITLE
support laravel 5.4.8 not installable

### ISSUE THREAD

**Issue by mubashirsiddique** [MisterPhilip/maintenance-mode#14]
I am unable to install for laravel 5.4.8 in my project saying:
** Installation request for laravel/framework (locked at v5.4.8, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.8].
    - Installation request for misterphilip/maintenance-mode ^1.0 -> satisfiable by misterphilip/maintenance-mode[1.0.0, 1.0.1, 1.0.2, 1.0.3].**

**Comment by MisterPhilip** [comment]
#15 should fix this, in the dev branch

**Comment by merfed** [comment]
While it can be installed on 5.4.x (specifically 5.4.21), It doesn't actually do anything, as in the middleware doesn't seem to be working.

**Comment by MisterPhilip** [comment]
I'm closing this out since 5.4 is a few versions old, but if you still need a backfill for 5.4 let me know. It'll take a little bit of work, but I can see if I can squeeze in some time to figure it out. Otherwise, the latest releases of this package will work on Laravel 5.5 & 5.6.
