### ISSUE TITLE
Currently uses L4 configuration method?

### ISSUE THREAD

**Issue by BenWoodford** [MisterPhilip/maintenance-mode#2]
I notice the package is currently using the config file path structure of Laravel 4. publish:config isn't a thing any more unfortunately and the way things are generally done now with configuration files is by having say, maintenancemode.php in the root config folder and then environment-specific things are put in the env file.

Any plans to change to this new method?

**Comment by MisterPhilip** [comment]
Yeah, I need to get this updated. I haven't had a chance since L5 was still in dev a few months ago.

**Comment by MisterPhilip** [comment]
I've pushed a new release that has the L5 config method (c453c37e106ea9c7adc295f2bc96ea4eb2d76292 has the changes).
