### ISSUE TITLE
Support for Laravel 5.7

### ISSUE THREAD

**Issue by TechTailor** [MisterPhilip/maintenance-mode#21]
As the title suggests, love your package but need support for it for Laravel 5.7

-Thanks

**Comment by TechTailor** [comment]
Hey, @MisterPhilip  can we get a merge on it and close this.

**Comment by MisterPhilip** [comment]
Sorry, let me see if I can review tonight and release. Looks fine to me for now, but need to test just to verify :)

**Comment by MisterPhilip** [comment]
`v1.2.3` now supports Laravel 5.7. Sorry for the delay!
