### ISSUE TITLE
Exception index 'view' not found

### ISSUE THREAD

**Issue by MarkAusten** [MisterPhilip/maintenance-mode#25]
In CheckForMaintenanceMode.php the above error is thrown at line 104. Viewing in debug mode there is no view index in the $data array.

Adding

`if( ! isset($data['view']))`
`{`
`	$data['view'] = $this->app['config']->get('maintenance mode.view');`
`}`

after line 80 cures the problem.

**Comment by MisterPhilip** [comment]
Hmmm, it should always have a `view` property, but I'll add this check. Thanks for the report!
