### ISSUE TITLE
Cannot install on Laravel 5.8 "Conclusion: remove nesbot/carbon 2.16.0"

### ISSUE THREAD

**Issue by lucasdcrk** [MisterPhilip/maintenance-mode#26]
Hi,

I'm on Laravel 5.8, when trying to install this package I have an error related to the version of Carbon (see attached screenshot)
![Screenshot_27](https://user-images.githubusercontent.com/17224437/54645817-7b45be80-4a9d-11e9-94b9-1337a8c1d75a.png)

Thanks for help!

**Comment by DerekBuntin** [comment]
You need to update your nestbot/carbon package in your json file as this package requires it.

Try `composer require nesbot/carbon` as that should update your version of the package or change your json manually to update your version to `^1.24`, then run composer update, once compelte proceed to install this package.

I hope this helps.

**Comment by MisterPhilip** [comment]
You should be able to install Carbon 1.24+ or 2.0+ now. Let me know if you're still running into issues.

**Comment by lucasdcrk** [comment]
It works, thanks!
