### ISSUE TITLE
ip exclude not working

### ISSUE THREAD

**Issue by ghost** [MisterPhilip/maintenance-mode#6]
i put my ip like

```
'exempt-ips' => ['123.88.456.157'],
```

but i still see the maintenance mode

**Comment by MisterPhilip** [comment]
What does your `config/maintenancemode.php` file look like? What version of Laravel are you on?

**Comment by ghost** [comment]
omg my bad it is working i forgot to set this

```
'exempt-environments' => ['production'],
```
