### ISSUE TITLE
Suggestion: Fire an event that can be hooked into

### ISSUE THREAD

**Issue by BenWoodford** [MisterPhilip/maintenance-mode#9]
Just a thought, an event that fires when you take the site down would be really handy. As far as I know Laravel doesn't have one by default, but it could allow sites that run mostly via web sockets to send off a "site shutting down" message to users, that kind of thing.

**Comment by MisterPhilip** [comment]
Huh, I thought I already had that in there but it looks like I missed it. I'll add it in!

**Comment by MisterPhilip** [comment]
Added in 1.0.3.
